### ISSUE TITLE
Terminal rendering typed in characters more than once

### ISSUE THREAD

**Issue by NilsHaldenwang** [skwp/dotfiles#683] opened 2016-01-05 10:26 UTC
When I am typing 'ssh' for example, the terminal shows 'sssssh'. It seems to randomly duplicate stuff and I have absolutely no idea what caused it. I updated my iTerm2 to the latest version and also reinstalled yadr, none of which helped. I then tried to disable yadr by moving my .yadr-Folder and the problem no longer occurred. Hence, I think it might have to do something with yadr. I am still on OS X Yosemite. Any suggestion on how to fix this is appreciated!

**Comment by NilsHaldenwang** [comment] 2016-01-07 09:13
Update: Works with the normal Mac Terminal.App, the weird stuff only happens with iTerm2. The combination of yadr and iTerm2 seems to cause this. Any suggestions on what I can do?

**Comment by skwp** [comment] 2016-07-23 19:59
Strange, i cannot reproduce nor have I heard from anyone else that this is a problem. Are you still seeing it?

**Comment by lfilho** [comment] 2017-06-05 17:19
We didn't have more complaints about this and it's been a while, so I'm taking the liberty of closing this issue, ok? Feel free to reopen it if needed

**Closed by lfilho** 2017-06-05 17:19 UTC
