### ISSUE TITLE
Vim too slow on El Capitan using iTerm2

### ISSUE THREAD

**Issue by fullofcaffeine** [skwp/dotfiles#670] opened 2015-10-20 16:44 UTC
Possibly related to https://github.com/skwp/dotfiles/issues/661.

I'm on a 2014 MacBook Pro Retina, 2.8Ghz i7, 16GB of RAM, 1TB SSD.
- `tmux 1.9a`
- `Vim 7.4.712` (http://pastie.org/private/9f7btjq54hx2u3foxaesvw)

On Yosemite, Vim's performance wasn't the best, but acceptable. I can't prove with benchmarks, but I can surely say that it became worst on El Capitan, for reasons I still can't understand. 

It seems related to the rendering engine - there seem to be slight delay on input processing too - not sure if iTerm or Vim-related. I couldn't isolate the problem yet. It became so painful that I was forced (unwillingly) to abandon my `yadr` tmux development environment in favor of `Sublime Text` for now.

I'm willing to gather some additional data about this and try to isolate the issue when I have some free time, but I'd like to know if other people are experiencing the same, if so, does anyone know what could be causing this slowness?

**Comment by nkgm** [comment] 2015-11-02 23:03
Just upgraded to El Capitan myself.  Scrolling felt painfully sluggish - both iTerm2 and Apple's Terminal. I managed to track it down to `lightline` - disabling it made scrolling as smooth as `vim -u NONE`. After further experimentation, I replaced those fancy unicode glyphs in `vim/settings/lightline.vim` with plain old ASCII ones et voila! Scrolling is fast again!

[This iTerm2 issue](https://gitlab.com/gnachman/iterm2/issues/2552) appears related (though old) but it's probably not, since Apple's own Terminal app is also affected.

**Comment by fullofcaffeine** [comment] 2015-11-23 05:46
Duplicate of: https://github.com/skwp/dotfiles/issues/661

**Comment by fullofcaffeine** [comment] 2015-11-23 05:47
@nkgm Hadn't seen this message. I'll try what you suggested. Thanks!

**Comment by fullofcaffeine** [comment] 2015-12-11 04:42
@nkgm The problem really seems to be Unicode glyphs, I wonder if it's related to Vim's rendering engine though?

**Comment by nkgm** [comment] 2015-12-14 10:37
@fullofcaffeine that wasn't the case in Mavericks though. Couple more notes:
* Even with unicode glyphs removed from lightline, scrolling performance deteriorates if NERDTree is open.
* Half-screen horizontal splits help, as you would expect.
* If all above fails, scroll in half-page increments (which I find myself use more often now and is a good habit anyway).

**Comment by romansalin** [comment] 2016-01-03 12:08
I have the same problem. I removed `separator` and `subseparator` settings from `settings/lightline.vim` and it started to work fine.

**Comment by nkgm** [comment] 2017-02-27 16:37
Bit of a late update: it is easy to overlook setting the right font containing the glyphs used by the various statuslines in iTerm's `Preferences/Profiles/Text`. Make sure you set a `* for Powerline` or similar font. The big gotcha here is that even if you neglect to do so **the glyphs will still show** courtesy of macOS font fallback, but **redrawing will be an order of magnitude slower**.

**Comment by lfilho** [comment] 2017-03-18 16:01
You think we could we close this by now, @fullofcaffeine @nkgm ?

**Comment by nkgm** [comment] 2017-03-19 13:06
👍

**Closed** 2017-06-05 17:11 UTC

**Comment by kafeltz** [comment] 2017-07-10 14:29
@nkgm I confirm, uninstalling lightline make vim on macos fast again. On my linux, do not happen any minor slow rendering, strange.

**Comment by nkgm** [comment] 2017-07-10 19:46
@kafeltz even though disabling lightline can help speed up TUI vim, it's usually not because lightline is slow, but due to its use of custom unicode glyphs in conjunction with an incorrect iTerm font setting. The root cause for me is outlined in https://github.com/skwp/dotfiles/issues/670#issuecomment-282773995.

**Comment by kafeltz** [comment] 2017-07-11 16:58
@nkgm you're right, It was basically a false positive info.
